/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.column_defines.conf
 */
#ifndef SWITCH_COLUMNS_H
#define SWITCH_COLUMNS_H

/* column number definitions for table comfStartTable */
       #define COLUMN_COMFSTINDEX		1
       #define COLUMN_COMFSTSTATE		2

/* column number definitions for table autoRestartTable */
       #define COLUMN_AUTORSTINDEX		1
       #define COLUMN_AUTORSTMODE		2
       #define COLUMN_AUTORSTDSTIP		3
       #define COLUMN_AUTORSTSPEEDDOWN		4
       #define COLUMN_AUTORSTSPEEDUP		5
       #define COLUMN_AUTORESTARTTIMEONHOUR		6
       #define COLUMN_AUTORESTARTTIMEONMIN		7
       #define COLUMN_AUTORESTARTTIMEOFFHOUR		8
       #define COLUMN_AUTORESTARTTIMEOFFMIN		9

/* column number definitions for table portPoeTable */
       #define COLUMN_PORTPOEINDEX		1
       #define COLUMN_PORTPOESTATE		2

/* column number definitions for table inputStatusTable */
       #define COLUMN_INPUTINDEX		1
       #define COLUMN_INPUTTYPE		2
       #define COLUMN_INPUTSTATE		3
       #define COLUMN_INPUTALARM		4

/* column number definitions for table poeStatusTable */
       #define COLUMN_PORTPOESTATUSINDEX		1
       #define COLUMN_PORTPOESTATUSSTATE		2
       #define COLUMN_PORTPOESTATUSPOWER		3

/* column number definitions for table autoRestartErrorsTable */
       #define COLUMN_ARPORTINDEX		1
       #define COLUMN_ARPORTSTATUS		2

/* column number definitions for table comfortStartStatusTable */
       #define COLUMN_CSPORTINDEX		1
       #define COLUMN_CSPORTSTATUS		2

/* column number definitions for table sfpStatusTable */
       #define COLUMN_PORTSFPINDEX		1
       #define COLUMN_PORTSFPPRESENT		2
       #define COLUMN_PORTSFPSIGNALDETECT		3
       #define COLUMN_PORTSFPVENDOR		4
       #define COLUMN_PORTSFPOUI		5
       #define COLUMN_PORTSFPPARTNUMBER		6
       #define COLUMN_PORTSFPREVISION		7
       #define COLUMN_PORTSFPTEMPERATURE		8
       #define COLUMN_PORTSFPVOLTAGE		9
       #define COLUMN_PORTSFPBIASCURRENT		10
       #define COLUMN_PORTSFPTXOUTPOWER		11
       #define COLUMN_PORTSFPTXOUTPOWERDB		12
       #define COLUMN_PORTSFPRXOUTPOWER		13
       #define COLUMN_PORTSFPRXOUTPOWERDB		14
#endif /* SWITCH_COLUMNS_H */
