/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "switch.h"

/** Initializes the switch module */
void
init_switch(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_comfStartTable();
    initialize_table_autoRestartTable();
    initialize_table_portPoeTable();
    initialize_table_inputStatusTable();
    initialize_table_poeStatusTable();
    initialize_table_autoRestartErrorsTable();
    initialize_table_comfortStartStatusTable();
    initialize_table_sfpStatusTable();
}


/** Initialize the comfStartTable table by defining its contents and how it's structured */
void
initialize_table_comfStartTable(void)
{
    const oid comfStartTable_oid[] = {1,3,6,1,4,1,42019,3,2,1,1,2};
    const size_t comfStartTable_oid_len   = OID_LENGTH(comfStartTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("switch:init", "initializing table comfStartTable\n"));

    reg = netsnmp_create_handler_registration(
              "comfStartTable",     comfStartTable_handler,
              comfStartTable_oid, comfStartTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: comfStIndex */
                           0);
    table_info->min_column = COLUMN_COMFSTINDEX;
    table_info->max_column = COLUMN_COMFSTSTATE;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = comfStartTable_get_first_data_point;
    iinfo->get_next_data_point  = comfStartTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct comfStartTable_entry {
    /* Index values */
    long comfStIndex;

    /* Column values */
    long comfStIndex;
    long old_comfStIndex;
    long comfStState;
    long old_comfStState;

    /* Illustrate using a simple linked list */
    int   valid;
    struct comfStartTable_entry *next;
};

struct comfStartTable_entry  *comfStartTable_head;

/* create a new row in the (unsorted) table */
struct comfStartTable_entry *
comfStartTable_createEntry(
                 long  comfStIndex,
                ) {
    struct comfStartTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct comfStartTable_entry);
    if (!entry)
        return NULL;

    entry->comfStIndex = comfStIndex;
    entry->next = comfStartTable_head;
    comfStartTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
comfStartTable_removeEntry( struct comfStartTable_entry *entry ) {
    struct comfStartTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = comfStartTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        comfStartTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
comfStartTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = comfStartTable_head;
    return comfStartTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
comfStartTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct comfStartTable_entry *entry = (struct comfStartTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->comfStIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the comfStartTable table */
int
comfStartTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct comfStartTable_entry          *table_entry;

    DEBUGMSGTL(("switch:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct comfStartTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_COMFSTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->comfStIndex);
                break;
            case COLUMN_COMFSTSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->comfStState);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct comfStartTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_COMFSTINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_COMFSTSTATE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct comfStartTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_COMFSTINDEX:
                table_entry->old_comfStIndex = table_entry->comfStIndex;
                table_entry->comfStIndex     = *request->requestvb->val.integer;
                break;
            case COLUMN_COMFSTSTATE:
                table_entry->old_comfStState = table_entry->comfStState;
                table_entry->comfStState     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct comfStartTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_COMFSTINDEX:
                table_entry->comfStIndex     = table_entry->old_comfStIndex;
                table_entry->old_comfStIndex = 0;
                break;
            case COLUMN_COMFSTSTATE:
                table_entry->comfStState     = table_entry->old_comfStState;
                table_entry->old_comfStState = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the autoRestartTable table by defining its contents and how it's structured */
void
initialize_table_autoRestartTable(void)
{
    const oid autoRestartTable_oid[] = {1,3,6,1,4,1,42019,3,2,1,2,1};
    const size_t autoRestartTable_oid_len   = OID_LENGTH(autoRestartTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("switch:init", "initializing table autoRestartTable\n"));

    reg = netsnmp_create_handler_registration(
              "autoRestartTable",     autoRestartTable_handler,
              autoRestartTable_oid, autoRestartTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: autoRstIndex */
                           0);
    table_info->min_column = COLUMN_AUTORSTINDEX;
    table_info->max_column = COLUMN_AUTORESTARTTIMEOFFMIN;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = autoRestartTable_get_first_data_point;
    iinfo->get_next_data_point  = autoRestartTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct autoRestartTable_entry {
    /* Index values */
    long autoRstIndex;

    /* Column values */
    long autoRstIndex;
    long old_autoRstIndex;
    long autoRstMode;
    long old_autoRstMode;
    in_addr_t autoRstDstIP;
    in_addr_t old_autoRstDstIP;
    long autoRstSpeedDown;
    long old_autoRstSpeedDown;
    long autoRstSpeedUp;
    long old_autoRstSpeedUp;
    long autoReStartTimeOnHour;
    long old_autoReStartTimeOnHour;
    long autoReStartTimeOnMin;
    long old_autoReStartTimeOnMin;
    long autoReStartTimeOffHour;
    long old_autoReStartTimeOffHour;
    long autoReStartTimeOffMin;
    long old_autoReStartTimeOffMin;

    /* Illustrate using a simple linked list */
    int   valid;
    struct autoRestartTable_entry *next;
};

struct autoRestartTable_entry  *autoRestartTable_head;

/* create a new row in the (unsorted) table */
struct autoRestartTable_entry *
autoRestartTable_createEntry(
                 long  autoRstIndex,
                ) {
    struct autoRestartTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct autoRestartTable_entry);
    if (!entry)
        return NULL;

    entry->autoRstIndex = autoRstIndex;
    entry->next = autoRestartTable_head;
    autoRestartTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
autoRestartTable_removeEntry( struct autoRestartTable_entry *entry ) {
    struct autoRestartTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = autoRestartTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        autoRestartTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
autoRestartTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = autoRestartTable_head;
    return autoRestartTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
autoRestartTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct autoRestartTable_entry *entry = (struct autoRestartTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->autoRstIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the autoRestartTable table */
int
autoRestartTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct autoRestartTable_entry          *table_entry;

    DEBUGMSGTL(("switch:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct autoRestartTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_AUTORSTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->autoRstIndex);
                break;
            case COLUMN_AUTORSTMODE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->autoRstMode);
                break;
            case COLUMN_AUTORSTDSTIP:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->autoRstDstIP);
                break;
            case COLUMN_AUTORSTSPEEDDOWN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->autoRstSpeedDown);
                break;
            case COLUMN_AUTORSTSPEEDUP:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->autoRstSpeedUp);
                break;
            case COLUMN_AUTORESTARTTIMEONHOUR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->autoReStartTimeOnHour);
                break;
            case COLUMN_AUTORESTARTTIMEONMIN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->autoReStartTimeOnMin);
                break;
            case COLUMN_AUTORESTARTTIMEOFFHOUR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->autoReStartTimeOffHour);
                break;
            case COLUMN_AUTORESTARTTIMEOFFMIN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->autoReStartTimeOffMin);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct autoRestartTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_AUTORSTINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_AUTORSTMODE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_AUTORSTDSTIP:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_AUTORSTSPEEDDOWN:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_AUTORSTSPEEDUP:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_AUTORESTARTTIMEONHOUR:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_AUTORESTARTTIMEONMIN:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_AUTORESTARTTIMEOFFHOUR:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_AUTORESTARTTIMEOFFMIN:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct autoRestartTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_AUTORSTINDEX:
                table_entry->old_autoRstIndex = table_entry->autoRstIndex;
                table_entry->autoRstIndex     = *request->requestvb->val.integer;
                break;
            case COLUMN_AUTORSTMODE:
                table_entry->old_autoRstMode = table_entry->autoRstMode;
                table_entry->autoRstMode     = *request->requestvb->val.integer;
                break;
            case COLUMN_AUTORSTDSTIP:
                table_entry->old_autoRstDstIP = table_entry->autoRstDstIP;
                table_entry->autoRstDstIP     = *request->requestvb->val.integer;
                break;
            case COLUMN_AUTORSTSPEEDDOWN:
                table_entry->old_autoRstSpeedDown = table_entry->autoRstSpeedDown;
                table_entry->autoRstSpeedDown     = *request->requestvb->val.integer;
                break;
            case COLUMN_AUTORSTSPEEDUP:
                table_entry->old_autoRstSpeedUp = table_entry->autoRstSpeedUp;
                table_entry->autoRstSpeedUp     = *request->requestvb->val.integer;
                break;
            case COLUMN_AUTORESTARTTIMEONHOUR:
                table_entry->old_autoReStartTimeOnHour = table_entry->autoReStartTimeOnHour;
                table_entry->autoReStartTimeOnHour     = *request->requestvb->val.integer;
                break;
            case COLUMN_AUTORESTARTTIMEONMIN:
                table_entry->old_autoReStartTimeOnMin = table_entry->autoReStartTimeOnMin;
                table_entry->autoReStartTimeOnMin     = *request->requestvb->val.integer;
                break;
            case COLUMN_AUTORESTARTTIMEOFFHOUR:
                table_entry->old_autoReStartTimeOffHour = table_entry->autoReStartTimeOffHour;
                table_entry->autoReStartTimeOffHour     = *request->requestvb->val.integer;
                break;
            case COLUMN_AUTORESTARTTIMEOFFMIN:
                table_entry->old_autoReStartTimeOffMin = table_entry->autoReStartTimeOffMin;
                table_entry->autoReStartTimeOffMin     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct autoRestartTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_AUTORSTINDEX:
                table_entry->autoRstIndex     = table_entry->old_autoRstIndex;
                table_entry->old_autoRstIndex = 0;
                break;
            case COLUMN_AUTORSTMODE:
                table_entry->autoRstMode     = table_entry->old_autoRstMode;
                table_entry->old_autoRstMode = 0;
                break;
            case COLUMN_AUTORSTDSTIP:
                table_entry->autoRstDstIP     = table_entry->old_autoRstDstIP;
                table_entry->old_autoRstDstIP = 0;
                break;
            case COLUMN_AUTORSTSPEEDDOWN:
                table_entry->autoRstSpeedDown     = table_entry->old_autoRstSpeedDown;
                table_entry->old_autoRstSpeedDown = 0;
                break;
            case COLUMN_AUTORSTSPEEDUP:
                table_entry->autoRstSpeedUp     = table_entry->old_autoRstSpeedUp;
                table_entry->old_autoRstSpeedUp = 0;
                break;
            case COLUMN_AUTORESTARTTIMEONHOUR:
                table_entry->autoReStartTimeOnHour     = table_entry->old_autoReStartTimeOnHour;
                table_entry->old_autoReStartTimeOnHour = 0;
                break;
            case COLUMN_AUTORESTARTTIMEONMIN:
                table_entry->autoReStartTimeOnMin     = table_entry->old_autoReStartTimeOnMin;
                table_entry->old_autoReStartTimeOnMin = 0;
                break;
            case COLUMN_AUTORESTARTTIMEOFFHOUR:
                table_entry->autoReStartTimeOffHour     = table_entry->old_autoReStartTimeOffHour;
                table_entry->old_autoReStartTimeOffHour = 0;
                break;
            case COLUMN_AUTORESTARTTIMEOFFMIN:
                table_entry->autoReStartTimeOffMin     = table_entry->old_autoReStartTimeOffMin;
                table_entry->old_autoReStartTimeOffMin = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the portPoeTable table by defining its contents and how it's structured */
void
initialize_table_portPoeTable(void)
{
    const oid portPoeTable_oid[] = {1,3,6,1,4,1,42019,3,2,1,3,1};
    const size_t portPoeTable_oid_len   = OID_LENGTH(portPoeTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("switch:init", "initializing table portPoeTable\n"));

    reg = netsnmp_create_handler_registration(
              "portPoeTable",     portPoeTable_handler,
              portPoeTable_oid, portPoeTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: portPoeIndex */
                           0);
    table_info->min_column = COLUMN_PORTPOEINDEX;
    table_info->max_column = COLUMN_PORTPOESTATE;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = portPoeTable_get_first_data_point;
    iinfo->get_next_data_point  = portPoeTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct portPoeTable_entry {
    /* Index values */
    long portPoeIndex;

    /* Column values */
    long portPoeIndex;
    long old_portPoeIndex;
    long portPoeState;
    long old_portPoeState;

    /* Illustrate using a simple linked list */
    int   valid;
    struct portPoeTable_entry *next;
};

struct portPoeTable_entry  *portPoeTable_head;

/* create a new row in the (unsorted) table */
struct portPoeTable_entry *
portPoeTable_createEntry(
                 long  portPoeIndex,
                ) {
    struct portPoeTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct portPoeTable_entry);
    if (!entry)
        return NULL;

    entry->portPoeIndex = portPoeIndex;
    entry->next = portPoeTable_head;
    portPoeTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
portPoeTable_removeEntry( struct portPoeTable_entry *entry ) {
    struct portPoeTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = portPoeTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        portPoeTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
portPoeTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = portPoeTable_head;
    return portPoeTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
portPoeTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct portPoeTable_entry *entry = (struct portPoeTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->portPoeIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the portPoeTable table */
int
portPoeTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct portPoeTable_entry          *table_entry;

    DEBUGMSGTL(("switch:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct portPoeTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTPOEINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portPoeIndex);
                break;
            case COLUMN_PORTPOESTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portPoeState);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct portPoeTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTPOEINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PORTPOESTATE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct portPoeTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTPOEINDEX:
                table_entry->old_portPoeIndex = table_entry->portPoeIndex;
                table_entry->portPoeIndex     = *request->requestvb->val.integer;
                break;
            case COLUMN_PORTPOESTATE:
                table_entry->old_portPoeState = table_entry->portPoeState;
                table_entry->portPoeState     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct portPoeTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTPOEINDEX:
                table_entry->portPoeIndex     = table_entry->old_portPoeIndex;
                table_entry->old_portPoeIndex = 0;
                break;
            case COLUMN_PORTPOESTATE:
                table_entry->portPoeState     = table_entry->old_portPoeState;
                table_entry->old_portPoeState = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the inputStatusTable table by defining its contents and how it's structured */
void
initialize_table_inputStatusTable(void)
{
    const oid inputStatusTable_oid[] = {1,3,6,1,4,1,42019,3,2,2,2,1};
    const size_t inputStatusTable_oid_len   = OID_LENGTH(inputStatusTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("switch:init", "initializing table inputStatusTable\n"));

    reg = netsnmp_create_handler_registration(
              "inputStatusTable",     inputStatusTable_handler,
              inputStatusTable_oid, inputStatusTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: inputIndex */
                           0);
    table_info->min_column = COLUMN_INPUTINDEX;
    table_info->max_column = COLUMN_INPUTALARM;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = inputStatusTable_get_first_data_point;
    iinfo->get_next_data_point  = inputStatusTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct inputStatusTable_entry {
    /* Index values */
    long inputIndex;

    /* Column values */
    long inputIndex;
    long old_inputIndex;
    long inputType;
    long inputState;
    long inputAlarm;

    /* Illustrate using a simple linked list */
    int   valid;
    struct inputStatusTable_entry *next;
};

struct inputStatusTable_entry  *inputStatusTable_head;

/* create a new row in the (unsorted) table */
struct inputStatusTable_entry *
inputStatusTable_createEntry(
                 long  inputIndex,
                ) {
    struct inputStatusTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct inputStatusTable_entry);
    if (!entry)
        return NULL;

    entry->inputIndex = inputIndex;
    entry->next = inputStatusTable_head;
    inputStatusTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
inputStatusTable_removeEntry( struct inputStatusTable_entry *entry ) {
    struct inputStatusTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = inputStatusTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        inputStatusTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
inputStatusTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = inputStatusTable_head;
    return inputStatusTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
inputStatusTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct inputStatusTable_entry *entry = (struct inputStatusTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->inputIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the inputStatusTable table */
int
inputStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct inputStatusTable_entry          *table_entry;

    DEBUGMSGTL(("switch:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct inputStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_INPUTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->inputIndex);
                break;
            case COLUMN_INPUTTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->inputType);
                break;
            case COLUMN_INPUTSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->inputState);
                break;
            case COLUMN_INPUTALARM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->inputAlarm);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct inputStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_INPUTINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct inputStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_INPUTINDEX:
                table_entry->old_inputIndex = table_entry->inputIndex;
                table_entry->inputIndex     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct inputStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_INPUTINDEX:
                table_entry->inputIndex     = table_entry->old_inputIndex;
                table_entry->old_inputIndex = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the poeStatusTable table by defining its contents and how it's structured */
void
initialize_table_poeStatusTable(void)
{
    const oid poeStatusTable_oid[] = {1,3,6,1,4,1,42019,3,2,2,5,1};
    const size_t poeStatusTable_oid_len   = OID_LENGTH(poeStatusTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("switch:init", "initializing table poeStatusTable\n"));

    reg = netsnmp_create_handler_registration(
              "poeStatusTable",     poeStatusTable_handler,
              poeStatusTable_oid, poeStatusTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: portPoeStatusIndex */
                           0);
    table_info->min_column = COLUMN_PORTPOESTATUSINDEX;
    table_info->max_column = COLUMN_PORTPOESTATUSPOWER;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = poeStatusTable_get_first_data_point;
    iinfo->get_next_data_point  = poeStatusTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct poeStatusTable_entry {
    /* Index values */
    long portPoeStatusIndex;

    /* Column values */
    long portPoeStatusIndex;
    long old_portPoeStatusIndex;
    long portPoeStatusState;
    long portPoeStatusPower;

    /* Illustrate using a simple linked list */
    int   valid;
    struct poeStatusTable_entry *next;
};

struct poeStatusTable_entry  *poeStatusTable_head;

/* create a new row in the (unsorted) table */
struct poeStatusTable_entry *
poeStatusTable_createEntry(
                 long  portPoeStatusIndex,
                ) {
    struct poeStatusTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct poeStatusTable_entry);
    if (!entry)
        return NULL;

    entry->portPoeStatusIndex = portPoeStatusIndex;
    entry->next = poeStatusTable_head;
    poeStatusTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
poeStatusTable_removeEntry( struct poeStatusTable_entry *entry ) {
    struct poeStatusTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = poeStatusTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        poeStatusTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
poeStatusTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = poeStatusTable_head;
    return poeStatusTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
poeStatusTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct poeStatusTable_entry *entry = (struct poeStatusTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->portPoeStatusIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the poeStatusTable table */
int
poeStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct poeStatusTable_entry          *table_entry;

    DEBUGMSGTL(("switch:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct poeStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTPOESTATUSINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portPoeStatusIndex);
                break;
            case COLUMN_PORTPOESTATUSSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portPoeStatusState);
                break;
            case COLUMN_PORTPOESTATUSPOWER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portPoeStatusPower);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct poeStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTPOESTATUSINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct poeStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTPOESTATUSINDEX:
                table_entry->old_portPoeStatusIndex = table_entry->portPoeStatusIndex;
                table_entry->portPoeStatusIndex     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct poeStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTPOESTATUSINDEX:
                table_entry->portPoeStatusIndex     = table_entry->old_portPoeStatusIndex;
                table_entry->old_portPoeStatusIndex = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the autoRestartErrorsTable table by defining its contents and how it's structured */
void
initialize_table_autoRestartErrorsTable(void)
{
    const oid autoRestartErrorsTable_oid[] = {1,3,6,1,4,1,42019,3,2,2,6,1,1};
    const size_t autoRestartErrorsTable_oid_len   = OID_LENGTH(autoRestartErrorsTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("switch:init", "initializing table autoRestartErrorsTable\n"));

    reg = netsnmp_create_handler_registration(
              "autoRestartErrorsTable",     autoRestartErrorsTable_handler,
              autoRestartErrorsTable_oid, autoRestartErrorsTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: arPortIndex */
                           0);
    table_info->min_column = COLUMN_ARPORTINDEX;
    table_info->max_column = COLUMN_ARPORTSTATUS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = autoRestartErrorsTable_get_first_data_point;
    iinfo->get_next_data_point  = autoRestartErrorsTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct autoRestartErrorsTable_entry {
    /* Index values */
    long arPortIndex;

    /* Column values */
    long arPortIndex;
    long old_arPortIndex;
    long arPortStatus;

    /* Illustrate using a simple linked list */
    int   valid;
    struct autoRestartErrorsTable_entry *next;
};

struct autoRestartErrorsTable_entry  *autoRestartErrorsTable_head;

/* create a new row in the (unsorted) table */
struct autoRestartErrorsTable_entry *
autoRestartErrorsTable_createEntry(
                 long  arPortIndex,
                ) {
    struct autoRestartErrorsTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct autoRestartErrorsTable_entry);
    if (!entry)
        return NULL;

    entry->arPortIndex = arPortIndex;
    entry->next = autoRestartErrorsTable_head;
    autoRestartErrorsTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
autoRestartErrorsTable_removeEntry( struct autoRestartErrorsTable_entry *entry ) {
    struct autoRestartErrorsTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = autoRestartErrorsTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        autoRestartErrorsTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
autoRestartErrorsTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = autoRestartErrorsTable_head;
    return autoRestartErrorsTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
autoRestartErrorsTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct autoRestartErrorsTable_entry *entry = (struct autoRestartErrorsTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->arPortIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the autoRestartErrorsTable table */
int
autoRestartErrorsTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct autoRestartErrorsTable_entry          *table_entry;

    DEBUGMSGTL(("switch:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct autoRestartErrorsTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ARPORTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->arPortIndex);
                break;
            case COLUMN_ARPORTSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->arPortStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct autoRestartErrorsTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ARPORTINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct autoRestartErrorsTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ARPORTINDEX:
                table_entry->old_arPortIndex = table_entry->arPortIndex;
                table_entry->arPortIndex     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct autoRestartErrorsTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ARPORTINDEX:
                table_entry->arPortIndex     = table_entry->old_arPortIndex;
                table_entry->old_arPortIndex = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the comfortStartStatusTable table by defining its contents and how it's structured */
void
initialize_table_comfortStartStatusTable(void)
{
    const oid comfortStartStatusTable_oid[] = {1,3,6,1,4,1,42019,3,2,2,6,2,1};
    const size_t comfortStartStatusTable_oid_len   = OID_LENGTH(comfortStartStatusTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("switch:init", "initializing table comfortStartStatusTable\n"));

    reg = netsnmp_create_handler_registration(
              "comfortStartStatusTable",     comfortStartStatusTable_handler,
              comfortStartStatusTable_oid, comfortStartStatusTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: csPortIndex */
                           0);
    table_info->min_column = COLUMN_CSPORTINDEX;
    table_info->max_column = COLUMN_CSPORTSTATUS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = comfortStartStatusTable_get_first_data_point;
    iinfo->get_next_data_point  = comfortStartStatusTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct comfortStartStatusTable_entry {
    /* Index values */
    long csPortIndex;

    /* Column values */
    long csPortIndex;
    long old_csPortIndex;
    long csPortStatus;

    /* Illustrate using a simple linked list */
    int   valid;
    struct comfortStartStatusTable_entry *next;
};

struct comfortStartStatusTable_entry  *comfortStartStatusTable_head;

/* create a new row in the (unsorted) table */
struct comfortStartStatusTable_entry *
comfortStartStatusTable_createEntry(
                 long  csPortIndex,
                ) {
    struct comfortStartStatusTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct comfortStartStatusTable_entry);
    if (!entry)
        return NULL;

    entry->csPortIndex = csPortIndex;
    entry->next = comfortStartStatusTable_head;
    comfortStartStatusTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
comfortStartStatusTable_removeEntry( struct comfortStartStatusTable_entry *entry ) {
    struct comfortStartStatusTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = comfortStartStatusTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        comfortStartStatusTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
comfortStartStatusTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = comfortStartStatusTable_head;
    return comfortStartStatusTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
comfortStartStatusTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct comfortStartStatusTable_entry *entry = (struct comfortStartStatusTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->csPortIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the comfortStartStatusTable table */
int
comfortStartStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct comfortStartStatusTable_entry          *table_entry;

    DEBUGMSGTL(("switch:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct comfortStartStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_CSPORTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->csPortIndex);
                break;
            case COLUMN_CSPORTSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->csPortStatus);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct comfortStartStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_CSPORTINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct comfortStartStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_CSPORTINDEX:
                table_entry->old_csPortIndex = table_entry->csPortIndex;
                table_entry->csPortIndex     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct comfortStartStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_CSPORTINDEX:
                table_entry->csPortIndex     = table_entry->old_csPortIndex;
                table_entry->old_csPortIndex = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the sfpStatusTable table by defining its contents and how it's structured */
void
initialize_table_sfpStatusTable(void)
{
    const oid sfpStatusTable_oid[] = {1,3,6,1,4,1,42019,3,2,2,7,1};
    const size_t sfpStatusTable_oid_len   = OID_LENGTH(sfpStatusTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("switch:init", "initializing table sfpStatusTable\n"));

    reg = netsnmp_create_handler_registration(
              "sfpStatusTable",     sfpStatusTable_handler,
              sfpStatusTable_oid, sfpStatusTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: portSfpIndex */
                           0);
    table_info->min_column = COLUMN_PORTSFPINDEX;
    table_info->max_column = COLUMN_PORTSFPRXOUTPOWERDB;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = sfpStatusTable_get_first_data_point;
    iinfo->get_next_data_point  = sfpStatusTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct sfpStatusTable_entry {
    /* Index values */
    long portSfpIndex;

    /* Column values */
    long portSfpIndex;
    long old_portSfpIndex;
    long portSfpPresent;
    long portSfpSignalDetect;
     portSfpVendor;
     portSfpOui;
     portSfpPartNumber;
     portSfpRevision;
    long portSfpTemperature;
    long portSfpVoltage;
    long portSfpBiasCurrent;
    long portSfpTxOutPower;
    long portSfpTxOutPowerDb;
    long portSfpRxOutPower;
    long portSfpRxOutPowerDb;

    /* Illustrate using a simple linked list */
    int   valid;
    struct sfpStatusTable_entry *next;
};

struct sfpStatusTable_entry  *sfpStatusTable_head;

/* create a new row in the (unsorted) table */
struct sfpStatusTable_entry *
sfpStatusTable_createEntry(
                 long  portSfpIndex,
                ) {
    struct sfpStatusTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct sfpStatusTable_entry);
    if (!entry)
        return NULL;

    entry->portSfpIndex = portSfpIndex;
    entry->next = sfpStatusTable_head;
    sfpStatusTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
sfpStatusTable_removeEntry( struct sfpStatusTable_entry *entry ) {
    struct sfpStatusTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = sfpStatusTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        sfpStatusTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
sfpStatusTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = sfpStatusTable_head;
    return sfpStatusTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
sfpStatusTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct sfpStatusTable_entry *entry = (struct sfpStatusTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->portSfpIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the sfpStatusTable table */
int
sfpStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct sfpStatusTable_entry          *table_entry;

    DEBUGMSGTL(("switch:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct sfpStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTSFPINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portSfpIndex);
                break;
            case COLUMN_PORTSFPPRESENT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portSfpPresent);
                break;
            case COLUMN_PORTSFPSIGNALDETECT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portSfpSignalDetect);
                break;
            case COLUMN_PORTSFPVENDOR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ,
                                            table_entry->portSfpVendor);
                break;
            case COLUMN_PORTSFPOUI:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ,
                                            table_entry->portSfpOui);
                break;
            case COLUMN_PORTSFPPARTNUMBER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ,
                                            table_entry->portSfpPartNumber);
                break;
            case COLUMN_PORTSFPREVISION:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ,
                                            table_entry->portSfpRevision);
                break;
            case COLUMN_PORTSFPTEMPERATURE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portSfpTemperature);
                break;
            case COLUMN_PORTSFPVOLTAGE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portSfpVoltage);
                break;
            case COLUMN_PORTSFPBIASCURRENT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portSfpBiasCurrent);
                break;
            case COLUMN_PORTSFPTXOUTPOWER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portSfpTxOutPower);
                break;
            case COLUMN_PORTSFPTXOUTPOWERDB:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portSfpTxOutPowerDb);
                break;
            case COLUMN_PORTSFPRXOUTPOWER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portSfpRxOutPower);
                break;
            case COLUMN_PORTSFPRXOUTPOWERDB:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->portSfpRxOutPowerDb);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct sfpStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTSFPINDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct sfpStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTSFPINDEX:
                table_entry->old_portSfpIndex = table_entry->portSfpIndex;
                table_entry->portSfpIndex     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct sfpStatusTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PORTSFPINDEX:
                table_entry->portSfpIndex     = table_entry->old_portSfpIndex;
                table_entry->old_portSfpIndex = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
