/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.create-dataset.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "switch.h"

/** Initialize the comfStartTable table by defining its contents and how it's structured */
void
initialize_table_comfStartTable(void)
{
    const oid comfStartTable_oid[] = {1,3,6,1,4,1,42019,3,2,1,1,2};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("comfStartTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_comfStartTable",
                "adding indexes to table comfStartTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: comfStIndex */
                           0);

    DEBUGMSGTL(("initialize_table_comfStartTable",
                "adding column types to table comfStartTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_COMFSTINDEX, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_COMFSTSTATE, ASN_INTEGER, 1,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change comfStartTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("comfStartTable", comfStartTable_handler,
                                                        comfStartTable_oid,
                                                        OID_LENGTH(comfStartTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}
/** Initialize the autoRestartTable table by defining its contents and how it's structured */
void
initialize_table_autoRestartTable(void)
{
    const oid autoRestartTable_oid[] = {1,3,6,1,4,1,42019,3,2,1,2,1};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("autoRestartTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_autoRestartTable",
                "adding indexes to table autoRestartTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: autoRstIndex */
                           0);

    DEBUGMSGTL(("initialize_table_autoRestartTable",
                "adding column types to table autoRestartTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_AUTORSTINDEX, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_AUTORSTMODE, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_AUTORSTDSTIP, ASN_IPADDRESS, 1,
                                            NULL, 0,
                                            COLUMN_AUTORSTSPEEDDOWN, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_AUTORSTSPEEDUP, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_AUTORESTARTTIMEONHOUR, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_AUTORESTARTTIMEONMIN, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_AUTORESTARTTIMEOFFHOUR, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_AUTORESTARTTIMEOFFMIN, ASN_INTEGER, 1,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change autoRestartTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("autoRestartTable", autoRestartTable_handler,
                                                        autoRestartTable_oid,
                                                        OID_LENGTH(autoRestartTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}
/** Initialize the portPoeTable table by defining its contents and how it's structured */
void
initialize_table_portPoeTable(void)
{
    const oid portPoeTable_oid[] = {1,3,6,1,4,1,42019,3,2,1,3,1};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("portPoeTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_portPoeTable",
                "adding indexes to table portPoeTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: portPoeIndex */
                           0);

    DEBUGMSGTL(("initialize_table_portPoeTable",
                "adding column types to table portPoeTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_PORTPOEINDEX, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_PORTPOESTATE, ASN_INTEGER, 1,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change portPoeTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("portPoeTable", portPoeTable_handler,
                                                        portPoeTable_oid,
                                                        OID_LENGTH(portPoeTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}
/** Initialize the inputStatusTable table by defining its contents and how it's structured */
void
initialize_table_inputStatusTable(void)
{
    const oid inputStatusTable_oid[] = {1,3,6,1,4,1,42019,3,2,2,2,1};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("inputStatusTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_inputStatusTable",
                "adding indexes to table inputStatusTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: inputIndex */
                           0);

    DEBUGMSGTL(("initialize_table_inputStatusTable",
                "adding column types to table inputStatusTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_INPUTINDEX, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_INPUTTYPE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_INPUTSTATE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_INPUTALARM, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change inputStatusTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("inputStatusTable", inputStatusTable_handler,
                                                        inputStatusTable_oid,
                                                        OID_LENGTH(inputStatusTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}
/** Initialize the poeStatusTable table by defining its contents and how it's structured */
void
initialize_table_poeStatusTable(void)
{
    const oid poeStatusTable_oid[] = {1,3,6,1,4,1,42019,3,2,2,5,1};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("poeStatusTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_poeStatusTable",
                "adding indexes to table poeStatusTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: portPoeStatusIndex */
                           0);

    DEBUGMSGTL(("initialize_table_poeStatusTable",
                "adding column types to table poeStatusTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_PORTPOESTATUSINDEX, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_PORTPOESTATUSSTATE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_PORTPOESTATUSPOWER, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change poeStatusTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("poeStatusTable", poeStatusTable_handler,
                                                        poeStatusTable_oid,
                                                        OID_LENGTH(poeStatusTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}
/** Initialize the autoRestartErrorsTable table by defining its contents and how it's structured */
void
initialize_table_autoRestartErrorsTable(void)
{
    const oid autoRestartErrorsTable_oid[] = {1,3,6,1,4,1,42019,3,2,2,6,1,1};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("autoRestartErrorsTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_autoRestartErrorsTable",
                "adding indexes to table autoRestartErrorsTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: arPortIndex */
                           0);

    DEBUGMSGTL(("initialize_table_autoRestartErrorsTable",
                "adding column types to table autoRestartErrorsTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_ARPORTINDEX, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_ARPORTSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change autoRestartErrorsTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("autoRestartErrorsTable", autoRestartErrorsTable_handler,
                                                        autoRestartErrorsTable_oid,
                                                        OID_LENGTH(autoRestartErrorsTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}
/** Initialize the comfortStartStatusTable table by defining its contents and how it's structured */
void
initialize_table_comfortStartStatusTable(void)
{
    const oid comfortStartStatusTable_oid[] = {1,3,6,1,4,1,42019,3,2,2,6,2,1};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("comfortStartStatusTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_comfortStartStatusTable",
                "adding indexes to table comfortStartStatusTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: csPortIndex */
                           0);

    DEBUGMSGTL(("initialize_table_comfortStartStatusTable",
                "adding column types to table comfortStartStatusTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_CSPORTINDEX, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_CSPORTSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change comfortStartStatusTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("comfortStartStatusTable", comfortStartStatusTable_handler,
                                                        comfortStartStatusTable_oid,
                                                        OID_LENGTH(comfortStartStatusTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}
/** Initialize the sfpStatusTable table by defining its contents and how it's structured */
void
initialize_table_sfpStatusTable(void)
{
    const oid sfpStatusTable_oid[] = {1,3,6,1,4,1,42019,3,2,2,7,1};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("sfpStatusTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_sfpStatusTable",
                "adding indexes to table sfpStatusTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: portSfpIndex */
                           0);

    DEBUGMSGTL(("initialize_table_sfpStatusTable",
                "adding column types to table sfpStatusTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_PORTSFPINDEX, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_PORTSFPPRESENT, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPSIGNALDETECT, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPVENDOR, , 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPOUI, , 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPPARTNUMBER, , 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPREVISION, , 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPTEMPERATURE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPVOLTAGE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPBIASCURRENT, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPTXOUTPOWER, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPTXOUTPOWERDB, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPRXOUTPOWER, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_PORTSFPRXOUTPOWERDB, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change sfpStatusTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("sfpStatusTable", sfpStatusTable_handler,
                                                        sfpStatusTable_oid,
                                                        OID_LENGTH(sfpStatusTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the switch module */
void
init_switch(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_comfStartTable();
    initialize_table_autoRestartTable();
    initialize_table_portPoeTable();
    initialize_table_inputStatusTable();
    initialize_table_poeStatusTable();
    initialize_table_autoRestartErrorsTable();
    initialize_table_comfortStartStatusTable();
    initialize_table_sfpStatusTable();
}

/** handles requests for the comfStartTable table, if anything else needs to be done */
int
comfStartTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the autoRestartTable table, if anything else needs to be done */
int
autoRestartTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the portPoeTable table, if anything else needs to be done */
int
portPoeTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the inputStatusTable table, if anything else needs to be done */
int
inputStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the poeStatusTable table, if anything else needs to be done */
int
poeStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the autoRestartErrorsTable table, if anything else needs to be done */
int
autoRestartErrorsTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the comfortStartStatusTable table, if anything else needs to be done */
int
comfortStartStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}

/** handles requests for the sfpStatusTable table, if anything else needs to be done */
int
sfpStatusTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
