/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.int_watch.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "switch.h"

/*
 * The variables we want to tie the relevant OIDs to.
 * The agent will handle all GET and (if applicable) SET requests
 * to these variables automatically, changing the values as needed.
 */

long    comfortStartTime = 0;  /* XXX: set default value */
long    state = 0;  /* XXX: set default value */
long    upsModeAvalible = 0;  /* XXX: set default value */
long    upsPwrSource = 0;  /* XXX: set default value */
long    upsBatteryVoltage = 0;  /* XXX: set default value */
long    upsBatteryTime = 0;  /* XXX: set default value */
long    sensorConnected = 0;  /* XXX: set default value */
long    sensorTemperature = 0;  /* XXX: set default value */
long    sensorHumidity = 0;  /* XXX: set default value */
long    sensorTemperatureMin = 0;  /* XXX: set default value */
long    sensorTemperatureMax = 0;  /* XXX: set default value */
long    sensorHumidityMin = 0;  /* XXX: set default value */
long    sensorHumidityMax = 0;  /* XXX: set default value */

/*
 * Our initialization routine, called automatically by the agent 
 * (Note that the function name must match init_FILENAME()) 
 */
void
init_switch(void)
{
  netsnmp_handler_registration *reg;

    const oid comfortStartTime_oid[] = { 1,3,6,1,4,1,42019,3,2,1,1,1 };
  static netsnmp_watcher_info comfortStartTime_winfo;
    const oid state_oid[] = { 1,3,6,1,4,1,42019,3,2,1,4,1 };
  static netsnmp_watcher_info state_winfo;
    const oid upsModeAvalible_oid[] = { 1,3,6,1,4,1,42019,3,2,2,1,1 };
  static netsnmp_watcher_info upsModeAvalible_winfo;
    const oid upsPwrSource_oid[] = { 1,3,6,1,4,1,42019,3,2,2,1,2 };
  static netsnmp_watcher_info upsPwrSource_winfo;
    const oid upsBatteryVoltage_oid[] = { 1,3,6,1,4,1,42019,3,2,2,1,3 };
  static netsnmp_watcher_info upsBatteryVoltage_winfo;
    const oid upsBatteryTime_oid[] = { 1,3,6,1,4,1,42019,3,2,2,1,4 };
  static netsnmp_watcher_info upsBatteryTime_winfo;
  static netsnmp_watcher_info fwVersion_winfo;
    const oid sensorConnected_oid[] = { 1,3,6,1,4,1,42019,3,2,2,8,1 };
  static netsnmp_watcher_info sensorConnected_winfo;
    const oid sensorTemperature_oid[] = { 1,3,6,1,4,1,42019,3,2,2,8,2 };
  static netsnmp_watcher_info sensorTemperature_winfo;
    const oid sensorHumidity_oid[] = { 1,3,6,1,4,1,42019,3,2,2,8,3 };
  static netsnmp_watcher_info sensorHumidity_winfo;
    const oid sensorTemperatureMin_oid[] = { 1,3,6,1,4,1,42019,3,2,2,8,4 };
  static netsnmp_watcher_info sensorTemperatureMin_winfo;
    const oid sensorTemperatureMax_oid[] = { 1,3,6,1,4,1,42019,3,2,2,8,5 };
  static netsnmp_watcher_info sensorTemperatureMax_winfo;
    const oid sensorHumidityMin_oid[] = { 1,3,6,1,4,1,42019,3,2,2,8,6 };
  static netsnmp_watcher_info sensorHumidityMin_winfo;
    const oid sensorHumidityMax_oid[] = { 1,3,6,1,4,1,42019,3,2,2,8,7 };
  static netsnmp_watcher_info sensorHumidityMax_winfo;

  /*
   * a debugging statement.  Run the agent with -Dswitch to see
   * the output of this debugging statement. 
   */
  DEBUGMSGTL(("switch", "Initializing the switch module\n"));


    /*
     * Register scalar watchers for each of the MIB objects.
     * The ASN type and RO/RW status are taken from the MIB definition,
     * but can be adjusted if needed.
     *
     * In most circumstances, the scalar watcher will handle all
     * of the necessary processing.  But the NULL parameter in the
     * netsnmp_create_handler_registration() call can be used to
     * supply a user-provided handler if necessary.
     *
     * This approach can also be used to handle Counter64, string-
     * and OID-based watched scalars (although variable-sized writeable
     * objects will need some more specialised initialisation).
     */
    DEBUGMSGTL(("switch",
                "Initializing comfortStartTime scalar integer.  Default value = %d\n",
                comfortStartTime));
    reg = netsnmp_create_handler_registration(
             "comfortStartTime", NULL,
              comfortStartTime_oid, OID_LENGTH(comfortStartTime_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&comfortStartTime_winfo, &comfortStartTime, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &comfortStartTime_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched comfortStartTime" );
    }

    DEBUGMSGTL(("switch",
                "Initializing state scalar integer.  Default value = %d\n",
                state));
    reg = netsnmp_create_handler_registration(
             "state", NULL,
              state_oid, OID_LENGTH(state_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&state_winfo, &state, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &state_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched state" );
    }

    DEBUGMSGTL(("switch",
                "Initializing upsModeAvalible scalar integer.  Default value = %d\n",
                upsModeAvalible));
    reg = netsnmp_create_handler_registration(
             "upsModeAvalible", NULL,
              upsModeAvalible_oid, OID_LENGTH(upsModeAvalible_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&upsModeAvalible_winfo, &upsModeAvalible, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &upsModeAvalible_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched upsModeAvalible" );
    }

    DEBUGMSGTL(("switch",
                "Initializing upsPwrSource scalar integer.  Default value = %d\n",
                upsPwrSource));
    reg = netsnmp_create_handler_registration(
             "upsPwrSource", NULL,
              upsPwrSource_oid, OID_LENGTH(upsPwrSource_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&upsPwrSource_winfo, &upsPwrSource, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &upsPwrSource_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched upsPwrSource" );
    }

    DEBUGMSGTL(("switch",
                "Initializing upsBatteryVoltage scalar integer.  Default value = %d\n",
                upsBatteryVoltage));
    reg = netsnmp_create_handler_registration(
             "upsBatteryVoltage", NULL,
              upsBatteryVoltage_oid, OID_LENGTH(upsBatteryVoltage_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&upsBatteryVoltage_winfo, &upsBatteryVoltage, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &upsBatteryVoltage_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched upsBatteryVoltage" );
    }

    DEBUGMSGTL(("switch",
                "Initializing upsBatteryTime scalar integer.  Default value = %d\n",
                upsBatteryTime));
    reg = netsnmp_create_handler_registration(
             "upsBatteryTime", NULL,
              upsBatteryTime_oid, OID_LENGTH(upsBatteryTime_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&upsBatteryTime_winfo, &upsBatteryTime, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &upsBatteryTime_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched upsBatteryTime" );
    }

    DEBUGMSGTL(("switch",
                "Initializing sensorConnected scalar integer.  Default value = %d\n",
                sensorConnected));
    reg = netsnmp_create_handler_registration(
             "sensorConnected", NULL,
              sensorConnected_oid, OID_LENGTH(sensorConnected_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&sensorConnected_winfo, &sensorConnected, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &sensorConnected_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched sensorConnected" );
    }

    DEBUGMSGTL(("switch",
                "Initializing sensorTemperature scalar integer.  Default value = %d\n",
                sensorTemperature));
    reg = netsnmp_create_handler_registration(
             "sensorTemperature", NULL,
              sensorTemperature_oid, OID_LENGTH(sensorTemperature_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&sensorTemperature_winfo, &sensorTemperature, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &sensorTemperature_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched sensorTemperature" );
    }

    DEBUGMSGTL(("switch",
                "Initializing sensorHumidity scalar integer.  Default value = %d\n",
                sensorHumidity));
    reg = netsnmp_create_handler_registration(
             "sensorHumidity", NULL,
              sensorHumidity_oid, OID_LENGTH(sensorHumidity_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&sensorHumidity_winfo, &sensorHumidity, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &sensorHumidity_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched sensorHumidity" );
    }

    DEBUGMSGTL(("switch",
                "Initializing sensorTemperatureMin scalar integer.  Default value = %d\n",
                sensorTemperatureMin));
    reg = netsnmp_create_handler_registration(
             "sensorTemperatureMin", NULL,
              sensorTemperatureMin_oid, OID_LENGTH(sensorTemperatureMin_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&sensorTemperatureMin_winfo, &sensorTemperatureMin, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &sensorTemperatureMin_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched sensorTemperatureMin" );
    }

    DEBUGMSGTL(("switch",
                "Initializing sensorTemperatureMax scalar integer.  Default value = %d\n",
                sensorTemperatureMax));
    reg = netsnmp_create_handler_registration(
             "sensorTemperatureMax", NULL,
              sensorTemperatureMax_oid, OID_LENGTH(sensorTemperatureMax_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&sensorTemperatureMax_winfo, &sensorTemperatureMax, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &sensorTemperatureMax_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched sensorTemperatureMax" );
    }

    DEBUGMSGTL(("switch",
                "Initializing sensorHumidityMin scalar integer.  Default value = %d\n",
                sensorHumidityMin));
    reg = netsnmp_create_handler_registration(
             "sensorHumidityMin", NULL,
              sensorHumidityMin_oid, OID_LENGTH(sensorHumidityMin_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&sensorHumidityMin_winfo, &sensorHumidityMin, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &sensorHumidityMin_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched sensorHumidityMin" );
    }

    DEBUGMSGTL(("switch",
                "Initializing sensorHumidityMax scalar integer.  Default value = %d\n",
                sensorHumidityMax));
    reg = netsnmp_create_handler_registration(
             "sensorHumidityMax", NULL,
              sensorHumidityMax_oid, OID_LENGTH(sensorHumidityMax_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&sensorHumidityMax_winfo, &sensorHumidityMax, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &sensorHumidityMax_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched sensorHumidityMax" );
    }


  DEBUGMSGTL(("switch",
              "Done initalizing switch module\n"));
}
