/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.int_watch.conf
 */
#ifndef SWITCH_H
#define SWITCH_H

/* function declarations */
void init_switch(void);

#endif /* SWITCH_H */
