/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.old-api.conf
 */
#ifndef SWITCH_H
#define SWITCH_H

/* function declarations */
void init_switch(void);
FindVarMethod var_switch;
FindVarMethod var_comfStartTable;
FindVarMethod var_autoRestartTable;
FindVarMethod var_portPoeTable;
FindVarMethod var_inputStatusTable;
FindVarMethod var_poeStatusTable;
FindVarMethod var_autoRestartErrorsTable;
FindVarMethod var_comfortStartStatusTable;
FindVarMethod var_sfpStatusTable;
    WriteMethod write_comfortStartTime;
    WriteMethod write_state;
    WriteMethod write_sensorTemperatureMin;
    WriteMethod write_sensorTemperatureMax;
    WriteMethod write_sensorHumidityMin;
    WriteMethod write_sensorHumidityMax;
    WriteMethod write_comfStIndex;
    WriteMethod write_comfStState;
    WriteMethod write_autoRstIndex;
    WriteMethod write_autoRstMode;
    WriteMethod write_autoRstDstIP;
    WriteMethod write_autoRstSpeedDown;
    WriteMethod write_autoRstSpeedUp;
    WriteMethod write_autoReStartTimeOnHour;
    WriteMethod write_autoReStartTimeOnMin;
    WriteMethod write_autoReStartTimeOffHour;
    WriteMethod write_autoReStartTimeOffMin;
    WriteMethod write_portPoeIndex;
    WriteMethod write_portPoeState;
    WriteMethod write_inputIndex;
    WriteMethod write_portPoeStatusIndex;
    WriteMethod write_arPortIndex;
    WriteMethod write_csPortIndex;
    WriteMethod write_portSfpIndex;

#endif /* SWITCH_H */
