/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.old-api.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "switch.h"

/* 
 * switch_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid switch_variables_oid[] = { 1,3,6,1,4,1,42019,3 };

/* 
 * variable4 switch_variables:
 *   this variable defines function callbacks and type return information 
 *   for the switch mib section 
 */

struct variable4 switch_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */
#define COMFORTSTARTTIME		1
{COMFORTSTARTTIME,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_switch, 4,  { 2,1,1,1 }},
#define STATE		2
{STATE,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_switch, 4,  { 2,1,4,1 }},
#define UPSMODEAVALIBLE		3
{UPSMODEAVALIBLE,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_switch, 4,  { 2,2,1,1 }},
#define UPSPWRSOURCE		4
{UPSPWRSOURCE,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_switch, 4,  { 2,2,1,2 }},
#define UPSBATTERYVOLTAGE		5
{UPSBATTERYVOLTAGE,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_switch, 4,  { 2,2,1,3 }},
#define UPSBATTERYTIME		6
{UPSBATTERYTIME,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_switch, 4,  { 2,2,1,4 }},
#define FWVERSION		7
{FWVERSION,  ASN_OCTET_STR,  NETSNMP_OLDAPI_RONLY,
 var_switch, 4,  { 2,2,3,1 }},
#define SENSORCONNECTED		8
{SENSORCONNECTED,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_switch, 4,  { 2,2,8,1 }},
#define SENSORTEMPERATURE		9
{SENSORTEMPERATURE,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_switch, 4,  { 2,2,8,2 }},
#define SENSORHUMIDITY		10
{SENSORHUMIDITY,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_switch, 4,  { 2,2,8,3 }},
#define SENSORTEMPERATUREMIN		11
{SENSORTEMPERATUREMIN,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_switch, 4,  { 2,2,8,4 }},
#define SENSORTEMPERATUREMAX		12
{SENSORTEMPERATUREMAX,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_switch, 4,  { 2,2,8,5 }},
#define SENSORHUMIDITYMIN		13
{SENSORHUMIDITYMIN,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_switch, 4,  { 2,2,8,6 }},
#define SENSORHUMIDITYMAX		14
{SENSORHUMIDITYMAX,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_switch, 4,  { 2,2,8,7 }},

#define COMFSTINDEX		1
{COMFSTINDEX,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_comfStartTable, 6,  { 2,1,1,2 , 1, 1 }},
#define COMFSTSTATE		2
{COMFSTSTATE,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_comfStartTable, 6,  { 2,1,1,2 , 1, 2 }},
#define AUTORSTINDEX		1
{AUTORSTINDEX,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_autoRestartTable, 6,  { 2,1,2,1 , 1, 1 }},
#define AUTORSTMODE		2
{AUTORSTMODE,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_autoRestartTable, 6,  { 2,1,2,1 , 1, 2 }},
#define AUTORSTDSTIP		3
{AUTORSTDSTIP,  ASN_IPADDRESS,  NETSNMP_OLDAPI_RWRITE,
 var_autoRestartTable, 6,  { 2,1,2,1 , 1, 3 }},
#define AUTORSTSPEEDDOWN		4
{AUTORSTSPEEDDOWN,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_autoRestartTable, 6,  { 2,1,2,1 , 1, 4 }},
#define AUTORSTSPEEDUP		5
{AUTORSTSPEEDUP,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_autoRestartTable, 6,  { 2,1,2,1 , 1, 5 }},
#define AUTORESTARTTIMEONHOUR		6
{AUTORESTARTTIMEONHOUR,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_autoRestartTable, 6,  { 2,1,2,1 , 1, 6 }},
#define AUTORESTARTTIMEONMIN		7
{AUTORESTARTTIMEONMIN,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_autoRestartTable, 6,  { 2,1,2,1 , 1, 7 }},
#define AUTORESTARTTIMEOFFHOUR		8
{AUTORESTARTTIMEOFFHOUR,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_autoRestartTable, 6,  { 2,1,2,1 , 1, 8 }},
#define AUTORESTARTTIMEOFFMIN		9
{AUTORESTARTTIMEOFFMIN,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_autoRestartTable, 6,  { 2,1,2,1 , 1, 9 }},
#define PORTPOEINDEX		1
{PORTPOEINDEX,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_portPoeTable, 6,  { 2,1,3,1 , 1, 1 }},
#define PORTPOESTATE		2
{PORTPOESTATE,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_portPoeTable, 6,  { 2,1,3,1 , 1, 2 }},
#define INPUTINDEX		1
{INPUTINDEX,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_inputStatusTable, 6,  { 2,2,2,1 , 1, 1 }},
#define INPUTTYPE		2
{INPUTTYPE,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_inputStatusTable, 6,  { 2,2,2,1 , 1, 2 }},
#define INPUTSTATE		3
{INPUTSTATE,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_inputStatusTable, 6,  { 2,2,2,1 , 1, 3 }},
#define INPUTALARM		4
{INPUTALARM,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_inputStatusTable, 6,  { 2,2,2,1 , 1, 4 }},
#define PORTPOESTATUSINDEX		1
{PORTPOESTATUSINDEX,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_poeStatusTable, 6,  { 2,2,5,1 , 1, 1 }},
#define PORTPOESTATUSSTATE		2
{PORTPOESTATUSSTATE,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_poeStatusTable, 6,  { 2,2,5,1 , 1, 2 }},
#define PORTPOESTATUSPOWER		3
{PORTPOESTATUSPOWER,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_poeStatusTable, 6,  { 2,2,5,1 , 1, 3 }},
#define ARPORTINDEX		1
{ARPORTINDEX,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_autoRestartErrorsTable, 7,  { 2,2,6,1,1 , 1, 1 }},
#define ARPORTSTATUS		2
{ARPORTSTATUS,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_autoRestartErrorsTable, 7,  { 2,2,6,1,1 , 1, 2 }},
#define CSPORTINDEX		1
{CSPORTINDEX,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_comfortStartStatusTable, 7,  { 2,2,6,2,1 , 1, 1 }},
#define CSPORTSTATUS		2
{CSPORTSTATUS,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_comfortStartStatusTable, 7,  { 2,2,6,2,1 , 1, 2 }},
#define PORTSFPINDEX		1
{PORTSFPINDEX,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 1 }},
#define PORTSFPPRESENT		2
{PORTSFPPRESENT,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 2 }},
#define PORTSFPSIGNALDETECT		3
{PORTSFPSIGNALDETECT,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 3 }},
#define PORTSFPVENDOR		4
{PORTSFPVENDOR,  ,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 4 }},
#define PORTSFPOUI		5
{PORTSFPOUI,  ,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 5 }},
#define PORTSFPPARTNUMBER		6
{PORTSFPPARTNUMBER,  ,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 6 }},
#define PORTSFPREVISION		7
{PORTSFPREVISION,  ,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 7 }},
#define PORTSFPTEMPERATURE		8
{PORTSFPTEMPERATURE,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 8 }},
#define PORTSFPVOLTAGE		9
{PORTSFPVOLTAGE,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 9 }},
#define PORTSFPBIASCURRENT		10
{PORTSFPBIASCURRENT,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 10 }},
#define PORTSFPTXOUTPOWER		11
{PORTSFPTXOUTPOWER,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 11 }},
#define PORTSFPTXOUTPOWERDB		12
{PORTSFPTXOUTPOWERDB,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 12 }},
#define PORTSFPRXOUTPOWER		13
{PORTSFPRXOUTPOWER,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 13 }},
#define PORTSFPRXOUTPOWERDB		14
{PORTSFPRXOUTPOWERDB,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_sfpStatusTable, 6,  { 2,2,7,1 , 1, 14 }},
};
/*    (L = length of the oidsuffix) */


/** Initializes the switch module */
void
init_switch(void)
{

    DEBUGMSGTL(("switch", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("switch", switch_variables, variable4,
               switch_variables_oid);

    /* place any other initialization junk you need here */
}

/*
 * var_switch():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_switch(struct variable *vp, 
                oid     *name, 
                size_t  *length, 
                int     exact, 
                size_t  *var_len, 
                WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case COMFORTSTARTTIME:
        *write_method = write_comfortStartTime;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case STATE:
        *write_method = write_state;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case UPSMODEAVALIBLE:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case UPSPWRSOURCE:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case UPSBATTERYVOLTAGE:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case UPSBATTERYTIME:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case FWVERSION:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SENSORCONNECTED:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SENSORTEMPERATURE:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SENSORHUMIDITY:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SENSORTEMPERATUREMIN:
        *write_method = write_sensorTemperatureMin;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SENSORTEMPERATUREMAX:
        *write_method = write_sensorTemperatureMax;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SENSORHUMIDITYMIN:
        *write_method = write_sensorHumidityMin;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SENSORHUMIDITYMAX:
        *write_method = write_sensorHumidityMax;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}


/*
 * var_comfStartTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_switch above.
 */
unsigned char *
var_comfStartTable(struct variable *vp,
    	    oid     *name,
    	    size_t  *length,
    	    int     exact,
    	    size_t  *var_len,
    	    WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /* 
   * This assumes that the table is a 'simple' table.
   *	See the implementation documentation for the meaning of this.
   *	You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *	you will need to provide the replacement code yourself.
   *	Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case COMFSTINDEX:
        *write_method = write_comfStIndex;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case COMFSTSTATE:
        *write_method = write_comfStState;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_autoRestartTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_switch above.
 */
unsigned char *
var_autoRestartTable(struct variable *vp,
    	    oid     *name,
    	    size_t  *length,
    	    int     exact,
    	    size_t  *var_len,
    	    WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /* 
   * This assumes that the table is a 'simple' table.
   *	See the implementation documentation for the meaning of this.
   *	You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *	you will need to provide the replacement code yourself.
   *	Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case AUTORSTINDEX:
        *write_method = write_autoRstIndex;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case AUTORSTMODE:
        *write_method = write_autoRstMode;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case AUTORSTDSTIP:
        *write_method = write_autoRstDstIP;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case AUTORSTSPEEDDOWN:
        *write_method = write_autoRstSpeedDown;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case AUTORSTSPEEDUP:
        *write_method = write_autoRstSpeedUp;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case AUTORESTARTTIMEONHOUR:
        *write_method = write_autoReStartTimeOnHour;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case AUTORESTARTTIMEONMIN:
        *write_method = write_autoReStartTimeOnMin;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case AUTORESTARTTIMEOFFHOUR:
        *write_method = write_autoReStartTimeOffHour;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case AUTORESTARTTIMEOFFMIN:
        *write_method = write_autoReStartTimeOffMin;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_portPoeTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_switch above.
 */
unsigned char *
var_portPoeTable(struct variable *vp,
    	    oid     *name,
    	    size_t  *length,
    	    int     exact,
    	    size_t  *var_len,
    	    WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /* 
   * This assumes that the table is a 'simple' table.
   *	See the implementation documentation for the meaning of this.
   *	You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *	you will need to provide the replacement code yourself.
   *	Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case PORTPOEINDEX:
        *write_method = write_portPoeIndex;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTPOESTATE:
        *write_method = write_portPoeState;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_inputStatusTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_switch above.
 */
unsigned char *
var_inputStatusTable(struct variable *vp,
    	    oid     *name,
    	    size_t  *length,
    	    int     exact,
    	    size_t  *var_len,
    	    WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /* 
   * This assumes that the table is a 'simple' table.
   *	See the implementation documentation for the meaning of this.
   *	You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *	you will need to provide the replacement code yourself.
   *	Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case INPUTINDEX:
        *write_method = write_inputIndex;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case INPUTTYPE:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case INPUTSTATE:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case INPUTALARM:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_poeStatusTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_switch above.
 */
unsigned char *
var_poeStatusTable(struct variable *vp,
    	    oid     *name,
    	    size_t  *length,
    	    int     exact,
    	    size_t  *var_len,
    	    WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /* 
   * This assumes that the table is a 'simple' table.
   *	See the implementation documentation for the meaning of this.
   *	You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *	you will need to provide the replacement code yourself.
   *	Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case PORTPOESTATUSINDEX:
        *write_method = write_portPoeStatusIndex;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTPOESTATUSSTATE:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTPOESTATUSPOWER:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_autoRestartErrorsTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_switch above.
 */
unsigned char *
var_autoRestartErrorsTable(struct variable *vp,
    	    oid     *name,
    	    size_t  *length,
    	    int     exact,
    	    size_t  *var_len,
    	    WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /* 
   * This assumes that the table is a 'simple' table.
   *	See the implementation documentation for the meaning of this.
   *	You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *	you will need to provide the replacement code yourself.
   *	Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case ARPORTINDEX:
        *write_method = write_arPortIndex;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case ARPORTSTATUS:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_comfortStartStatusTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_switch above.
 */
unsigned char *
var_comfortStartStatusTable(struct variable *vp,
    	    oid     *name,
    	    size_t  *length,
    	    int     exact,
    	    size_t  *var_len,
    	    WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /* 
   * This assumes that the table is a 'simple' table.
   *	See the implementation documentation for the meaning of this.
   *	You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *	you will need to provide the replacement code yourself.
   *	Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case CSPORTINDEX:
        *write_method = write_csPortIndex;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case CSPORTSTATUS:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}
/*
 * var_sfpStatusTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_switch above.
 */
unsigned char *
var_sfpStatusTable(struct variable *vp,
    	    oid     *name,
    	    size_t  *length,
    	    int     exact,
    	    size_t  *var_len,
    	    WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /* 
   * This assumes that the table is a 'simple' table.
   *	See the implementation documentation for the meaning of this.
   *	You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *	you will need to provide the replacement code yourself.
   *	Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case PORTSFPINDEX:
        *write_method = write_portSfpIndex;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPPRESENT:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPSIGNALDETECT:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPVENDOR:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPOUI:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPPARTNUMBER:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPREVISION:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPTEMPERATURE:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPVOLTAGE:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPBIASCURRENT:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPTXOUTPOWER:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPTXOUTPOWERDB:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPRXOUTPOWER:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case PORTSFPRXOUTPOWERDB:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}



int
write_comfortStartTime(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_state(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_sensorTemperatureMin(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_sensorTemperatureMax(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_sensorHumidityMin(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_sensorHumidityMax(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_comfStIndex(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_comfStState(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_autoRstIndex(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_autoRstMode(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_autoRstDstIP(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    in_addr_t value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_IPADDRESS) {
              fprintf(stderr, "write to switch not ASN_IPADDRESS\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(in_addr_t)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (in_addr_t *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_autoRstSpeedDown(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_autoRstSpeedUp(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_autoReStartTimeOnHour(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_autoReStartTimeOnMin(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_autoReStartTimeOffHour(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_autoReStartTimeOffMin(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_portPoeIndex(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_portPoeState(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_inputIndex(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_portPoeStatusIndex(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_arPortIndex(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_csPortIndex(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
int
write_portSfpIndex(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to switch not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to switch: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}
