/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef SWITCH_H
#define SWITCH_H

/* function declarations */
void init_switch(void);
Netsnmp_Node_Handler handle_comfortStartTime;
Netsnmp_Node_Handler handle_state;
Netsnmp_Node_Handler handle_upsModeAvalible;
Netsnmp_Node_Handler handle_upsPwrSource;
Netsnmp_Node_Handler handle_upsBatteryVoltage;
Netsnmp_Node_Handler handle_upsBatteryTime;
Netsnmp_Node_Handler handle_fwVersion;
Netsnmp_Node_Handler handle_sensorConnected;
Netsnmp_Node_Handler handle_sensorTemperature;
Netsnmp_Node_Handler handle_sensorHumidity;
Netsnmp_Node_Handler handle_sensorTemperatureMin;
Netsnmp_Node_Handler handle_sensorTemperatureMax;
Netsnmp_Node_Handler handle_sensorHumidityMin;
Netsnmp_Node_Handler handle_sensorHumidityMax;

#endif /* SWITCH_H */
